"""Make face_id optional in PersonInfo

Revision ID: 79ccbf3a85a1
Revises: 690c29939fd4
Create Date: 2025-12-19 10:17:41.520611

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector 
import pgvector 


# revision identifiers, used by Alembic.
revision: str = '79ccbf3a85a1'
down_revision: Union[str, Sequence[str], None] = '690c29939fd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('image_data', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detected_faces',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('photo_id', sa.Integer(), nullable=True),
    sa.Column('x', sa.Integer(), nullable=False),
    sa.Column('y', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('face_image_data', sa.LargeBinary(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transcripts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('photo_id', sa.Integer(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('extracted_name', sa.String(), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('photo_id')
    )
    op.create_table('face_encodings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('face_id', sa.Integer(), nullable=False),
    sa.Column('encoding', pgvector.sqlalchemy.vector.VECTOR(dim=128), nullable=False),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['face_id'], ['detected_faces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('face_id')
    )
    op.create_table('person_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('face_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('conversation_context', sa.Text(), nullable=True),
    sa.Column('first_met_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('times_met', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['face_id'], ['detected_faces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('face_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('person_info')
    op.drop_table('face_encodings')
    op.drop_table('transcripts')
    op.drop_table('detected_faces')
    op.drop_table('photos')
    # ### end Alembic commands ###
